# Site settings
title: Divyanshu Grover
email: divyanshu1993@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software engineer at Microsoft India in Hyderabad. I've done my M.Tech. from IIT Bombay with focus being on Computer Graphics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://divyanshugrover.github.io/" # the base hostname & protocol for your site
twitter_username: DivyanshuGrover
github_username:  divyanshugrover

# Build settings
# markdown: kramdown

# Other options
# permalink: blog/:year/:month/:title/
jobtitle: "Software Engineer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: "https://plus.google.com/u/0/110288225974212014913"
# google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
# bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

gems:
  - jekyll-sitemap

theme: jekyll-theme-cayman

