# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Homepage of Divyanshu Grover
author: Divyanshu Grover
email: divyanshu1993@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Homepage of Divyanshu Grover
footer1: Software Engineer, Microsoft, Aug 16 - present
footer2: M.Tech., IIT Bombay, Jul 14 - Jun 16
footer3: B.E, Punjab University, Jul 10 - Jun 14
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://divyanshugrover.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-90399390-1

#Footer
twitter_username: DivyanshuGrover
github_username:  divyanshugrover
linkedin_username: divyanshugrover
instagram_username: divyanshu.grover
facebook_username: divyanshu.grover
youtube_username: DivyanshuGrover

#SEO
logo: favicon.jpg
social:
  name: Divyanshu Grover
  links:
    - https://www.facebook.com/divyanshu.grover
    - https://github.com/divyanshugrover
    - https://www.instagram.com/divyanshu.grover
    - https://www.linkedin.com/in/divyanshugrover
    - https://twitter.com/DivyanshuGrover
    - https://www.youtube.com/c/DivyanshuGrover
twitter:
  username: DivyanshuGrover

#Assets
insta_img: /assets/icon-instagram.png
construction_img: /assets/construction.jpg
acm_img: /assets/acm.gif

repository: divyanshugrover/divyanshugrover.github.io

# Build settings
markdown: kramdown
#theme: minima
#theme: jekyll-theme-cayman
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
